#!/bin/bash

PKGNAME="__PKGNAME__"

# Создаем виртуальное окружение и устанавливаем зависимости
cd /usr/local/bin/$PKGNAME
python3 -m venv myenv
source myenv/bin/activate
pip install --upgrade pip
pip install -r requirements.txt

# Проверяем наличие .env файла и создаем шаблон, если его нет
if [ ! -f /usr/local/bin/$PKGNAME/.env ]; then
    cat > /usr/local/bin/$PKGNAME/.env <<EOF
# Шаблон для .env файла
TELEGRAM_TOKEN=your_telegram_token
TELEGRAM_USER_ID=your_telegram_user_id
YANDEX_FOLDER_ID=your_yandex_folder_id
YANDEX_SPEECHKIT_TOKEN=your_yandex_token
YANDEX_GPT_APIKEY=your_yandex_gpt_apikey
SERVICE=todoist   # или yougile

TODOIST_TOKEN=your_todoist_token   # (только если используете Todoist)
TODOIST_DEFAULT_PROJECT_ID=your_todoist_project_id   # (только если используете Todoist)
TODOIST_DEFAULT_SECTION_ID=your_todoist_section_id   # (только если используете Todoist)

YOUGILE_TOKEN=your_yougile_token   # (только если используете Yougile)
YOUGILE_LOCATION=your_yougile_column_id   # (только если используете Yougile)
EOF
    echo "ВНИМАНИЕ: Заполните файл /usr/local/bin/$PKGNAME/.env своими токенами!"
fi

# Устанавливаем правильные права
chown -R root:root /usr/local/bin/$PKGNAME
chmod -R 755 /usr/local/bin/$PKGNAME
chown -R root:root /var/log/$PKGNAME
chmod -R 755 /var/log/$PKGNAME

# Перезагружаем systemd и включаем сервис
systemctl daemon-reload
systemctl enable $PKGNAME.service
systemctl start $PKGNAME.service

exit 0 